accounts/urls.py
from django.urls import path, include
from django.conf import settings
from rest_framework.authtoken.views import obtain_auth_token
from django.conf.urls.static import static
from rest_framework.authtoken import views as rest_framework_views
from rest_framework import routers
from rest_framework.authtoken import views

from .views import *
from . import views as local_views



app_name = 'accounts'

router = routers.DefaultRouter()
router.register(r'users', PersonViewSet)

urlpatterns = [
	path('join/', join, name='join'),
	path('auth-validation/', auth_validation, name='auth_validation'),
	path('soundcloud-login/', soundcloud_login, name='soundcloud_login'),
	path('cancel/', social_cancel),
	# path('register-email/', register_email, name='register_email'),
	path('', include(router.urls)),
	# path('test/', test),
	# path('get_auth_token/', rest_framework_views.obtain_auth_token, name='get_auth_token'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
# from rest_framework_expiring_authtoken import views
from .views import *



urlpatterns = [
    # path('', test_view, name='index'),
    path('logout', LogoutView.as_view(), name='home_logout'),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('tracks/', include('tracks.urls', namespace='tracks')),
    path('', include('social_django.urls', namespace='social')),
    path('callback/', callback_comp),
    path('player/', player),
    path('playlist/', include('playlists.urls', namespace='playlisy')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout
from django.views.generic import FormView, RedirectView
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.views.decorators.csrf import csrf_exempt
from social_django.models import UserSocialAuth
from django.conf import settings
from django.contrib import messages
# from rest_framework import viewsets
# from rest_framework import permissions


from tracks.permissions import IsOwnerOrReadOnly
from accounts.models import User
from accounts.views import auth_redirect
from rest_framework.authtoken.models import Token
# from .serializers import MeSerializer

# from rest_framework import status
# from rest_framework.response import Response

import requests
import json
import soundcloud

def test_view(request):
	return render(request, 'test.html')


def auth_view(request):
	return render(request, 'home.html', {'main_site' : settings.MAIN_URL})


class LogoutView(RedirectView):
	url = '//dopehotz.com'

	def get(self, request, *args, **kwargs):
		auth_logout(request)
		return super(LogoutView, self).get(request, *args, **kwargs)


def sc_view(request):
	# request.session['test'] = 'asss'
	return render(request, 'sc.html')

@csrf_exempt
def test_ajax(request):
	if not request.POST.get('oauth-token'):
		return redirect('//dopehotz.com'+settings.SOCIAL_AUTH_LOGIN_REDIRECT_URL+'#status=error&error_type=Not+Found+oauth+token')

	email = request.POST.get('email')
	if not email:
		return redirect('//dopehotz.com'+settings.SOCIAL_AUTH_LOGIN_REDIRECT_URL+'#status=error&error_type=Please+enter+your+e-mail')

	link = 'https://api.soundcloud.com/me?oauth_token='+request.POST.get('oauth-token')
	data = requests.get(link)
	if data.status_code != requests.codes.ok:
		return redirect('//dopehotz.com'+settings.SOCIAL_AUTH_LOGIN_REDIRECT_URL+'#status=error&error_type=Not+Found+user')

	data = data.json()
	user, created = User.objects.get_or_create(email=email)

	if created:
		user.username = data['username']
		user.soundcloud_url = data['permalink_url']
		user.profile_picture = data['avatar_url']
		user.save()

		social_auth = UserSocialAuth()
		social_auth.provider = 'soundcloud'
		social_auth.uid = data['id']
		social_auth.user_id = user.id
		social_auth.save()

		msg = settings.SOCIAL_AUTH_NEW_USER_REDIRECT_URL+"status=success&create=true&access_token="+get_user_token(user.id)
	else:
		if user.is_active:
			msg = settings.SOCIAL_AUTH_LOGIN_REDIRECT_URL+"#status=success&create=false&access_token="+get_user_token(user.id)
		else:
			msg = settings.SOCIAL_AUTH_LOGIN_REDIRECT_URL+"status=error&create=false&error_type=account+is+not+active"

	return redirect('//dopehotz.com'+msg)


def get_user_token(userid):
	token = Token.objects.get(user=userid)
	return token.key



def callback_comp(request):
	return render(request, 'auth_comp.html')

def test(request):
	return render(request, 'test.html')



def soundcloud_login(request):
	import soundcloud
	client = soundcloud.Client(client_id=settings.SOCIAL_AUTH_SOUNDCLOUD_KEY,
                           client_secret=settings.SOCIAL_AUTH_SOUNDCLOUD_SECRET,
                           redirect_uri='https://auth.dopehotz.com/callback/')
	return redirect(client.authorize_url())


def callback(request):
	if 'error' in request.GET:
		messages.add_message(request, messages.ERROR, '로그인이 취소 되었습니다.')
		return redirect('index')

	backend = request.session.get('social_auth_last_login_backend', None)

	if backend:
		# msg = settings.SOCIAL_AUTH_LOGIN_REDIRECT_URL+"#status=success&access_token="+get_user_token(request.session['_auth_user_id'])
		auth_logout(request)
		return auth_redirect(request, '#status=success&access_token='+get_user_token(request.session['_auth_user_id']))
	
		# return redirect('//dopehotz.com'+msg)
	

	code = request.GET.get('code', None)
	if code:
		client = soundcloud.Client(client_id=settings.SOCIAL_AUTH_SOUNDCLOUD_KEY,
                           client_secret=settings.SOCIAL_AUTH_SOUNDCLOUD_SECRET,
                           redirect_uri='https://auth.dopehotz.com/callback/')
		access_token = client.exchange_token(code)

		client = soundcloud.Client(access_token=access_token.obj['access_token'])
		current_user = client.get('/me')
		request.session['current_user'] = current_user.__dict__

	return redirect('accounts:auth_validation')


def session_check(request):
	if request.user.is_authenticated:
		return HttpResponse("{'session': True, 'uid': "+request.session['_auth_user_id']+"}")
	else:
		# result = 
		return HttpResponse("{'session': False}")


def player(request):
	return render(request, 'player.html')




	

templates/agree.html
{% extends "base.html" %}
{% block head_title %}DOPEHOTZ - 로그인{% endblock %}
{% block content %}
<div id="container">
    <div class="login_wrap">
        <div class="login_inner">
            <h2>로그인</h2>
            <p>#새로운_발견 #무한한_영감
                <br>도파츠와 함께 하세요.</p>
            <ul>
                <li><a class="soundcloud_login" href="{%url "soundcloud_login" %}">사운드클라우드 로그인</a></li>
                <li><a class="kakao_login" href="{%url "kakao_login" %}">카카오 로그인</a></li>
                <li><a class="naver_login" href="{%url "naver_login" %}"">네이버 로그인</a></li>
                <li><a class="facebook_login" href="{%url "facebook_login" %}">페이스북 로그인</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/auth_comp.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<script type="text/javascript">
	localStorage.setItem('user', /access_token=(.*)&?/.exec(location.href)[1]);
	self.close();
</script>
</body>
</html>

templates/auth_home.html
<!DOCTYPE html>
<html>
<head>
	<script src="https://connect.soundcloud.com/sdk/sdk-3.3.0.js"></script>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

</head>
<body>
{% if messages %}
<div>
    <ul>
    {% for message in messages %}
        <li>{{message}}</li>
    {% endfor %}
    </ul>
</div>
{% endif %}
{% load staticfiles %}
{{user}}<br>
<a href="{%url "soundcloud_login" %}"><img src="{%static 'images/btn-connect-sc-m.png'%}" alt=""></a>
<!-- <a href="javascript: soundcloud_login();">soundcloud-javascript</a> -->
<a href="{%url "kakao_login" %}">KAKAO</a>
<a href="{%url "naver_login" %}">NAVER</a>
<a href="{%url "facebook_login" %}">FACEBOOK</a>

{% if user.is_authenticated %}
<a href="{% url "home_logout" %}">Logout</a>
{% endif %}

<script>
SC.initialize({
	client_id: '7c76b10fd87a3f9cf91d51b9f8cf069c',
	redirect_uri: 'https://auth.dopehotz.com/callback/',
});

function soundcloud_login(){
    SC.connect().then(function() {
        return SC.get('/me');
    }).then(function(me) {
        alert('Hello, ' + me.username);
    });    
}


function getCookie(cname) {
    var name = cname + "=";
    var decodedCookie = decodeURIComponent(document.cookie);
    var ca = decodedCookie.split(';');
    for(var i = 0; i <ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0) == ' ') {
            c = c.substring(1);
        }
        if (c.indexOf(name) == 0) {
            return c.substring(name.length, c.length);
        }
    }
    return "";
}

redirectPost = function(location, args){
    var form = '';
    $.each( args, function( key, value ) {
        value = value.split('"').join('\"')
        form += '<input type="hidden" name="'+key+'" value="'+value+'">';
    });
    $('<form action="' + location + '" method="POST">' + form + '</form>').appendTo($(document.body)).submit();
}

var reg = /access_token=(.*)[&?]/;
if (reg.test(location.href)) {
	redirectPost('#', {'oauth-token': reg.exec(location.href)[1], 'csrfmiddlewaretoken': getCookie('csrftoken')});
}


</script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta name="theme-color" content="#242425" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="DOPEHOTZ">
    <title>{% block head_title %}{% endblock %}</title>
    <link rel="icon" sizes="192x192" href="/icon.png" />
    <link rel="apple-touch-icon" href="/icon.png">
    <meta name="msapplication-TileImage" content="icon.png">
    <meta name="msapplication-TileColor" content="#2F3BA2">
    {% load staticfiles %}
    <link href="{% static 'css/base.css'%}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/case.css'%}" rel="stylesheet" type="text/css" />
    <link rel="manifest" href="/manifest.json">
    <script src="//code.jquery.com/jquery-latest.min.js"></script>
    {% block extra_head %}
    {% endblock %}
</head>

<body>
  {% block body %}
  <!-- PC 버전 헤더 -->
    <div id="header">
        <div class="header_width">
            <a href="/">
                <!-- <div class="logo">DOPEHOTZ</div>-->
                <div class="logo"></div>
            </a>
        </div>
    </div>
    <!-- 모바일 버전 헤더 -->
    <div id="header_m">
        <a href="/">
            <div class="logo_m"></div>
        </a>
    </div>
    {% block content %}
    {% endblock %}
  {% endblock %}
    <div id="footer" style="margin-bottom:0; ">
        <p>copyright© DOPEHOTZ. all right reserved.</p>
    </div>
</body>

</html>

templates/callback.html
<!DOCTYPE html>
<html>
<head>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<title></title>
</head>
<body>
<script type="text/javascript">
function getCookie(cname) {
    var name = cname + "=";
    var decodedCookie = decodeURIComponent(document.cookie);
    var ca = decodedCookie.split(';');
    for(var i = 0; i <ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0) == ' ') {
            c = c.substring(1);
        }
        if (c.indexOf(name) == 0) {
            return c.substring(name.length, c.length);
        }
    }
    return "";
}
redirectPost = function(location, args){
    var form = '';
    $.each( args, function( key, value ) {
        value = value.split('"').join('\"')
        form += '<input type="hidden" name="'+key+'" value="'+value+'">';
    });
    $('<form action="' + location + '" method="POST">' + form + '</form>').appendTo($(document.body)).submit();
}

var reg = /access_token=(.*)[&?]/;
if (reg.test(location.href)) {
	redirectPost('{% url "accounts:soundcloud_login" %}', {'oauth-token': reg.exec(location.href)[1], 'csrfmiddlewaretoken': getCookie('csrftoken')});
}
</script>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block head_title %}DOPEHOTZ - 로그인{% endblock %}
{% block content %}
<div id="container">
    <div class="login_wrap">
        <div class="login_inner">
            {% if not user.is_authenticated %}
            <h2>로그인</h2>
            <p>#새로운_발견 #무한한_영감
                <br>도파츠와 함께 하세요.</p>
            <ul>
                <li><a class="soundcloud_login" href="{%url "soundcloud_login" %}">사운드클라우드 로그인</a></li>
                <li><a class="kakao_login" href="{%url "kakao_login" %}">카카오 로그인</a></li>
                <li><a class="naver_login" href="{%url "naver_login" %}"">네이버 로그인</a></li>
                <li><a class="facebook_login" href="{%url "facebook_login" %}">페이스북 로그인</a></li>
            </ul>
            {% else %}
            <ul>
                <li><a class="soundcloud_login" href="{% url "home_logout" %}">로그아웃</a></li>
            </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/player.html
<!DOCTYPE html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<html>
<head>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://connect.soundcloud.com/sdk/sdk-3.3.0.js"></script>

	<title></title>
</head>
<body>
	<div id="loading" style="display: none;">loading...</div>
	<div class="test123"><a href="#" id="player-button">play/stop</a></div>
	<div>
		<span id="before">before</span> | <span id="next">next</span>
	</div>
	<div>
		<span id="time" style="display: inline-block; width: 35px; text-align: left;">0:00</span> / <span id="total_time">0:00</span>
	</div>
	<div id="status"></div>
	<div id="list-view" style="margin-top: 10px;"></div>
	<!-- <input type="range" id="seek" name="" min="0" max="0" style="width: 500px;"> -->

	<canvas></canvas>
<script>
SC.initialize({
 	// client_id: '7c76b10fd87a3f9cf91d51b9f8cf069c'
 	client_id: 'N2eHz8D7GtXSl6fTtcGHdSJiS74xqOUI'
});

// console.log(player);
// stream track id 293
var track_list = [
	328602933, 181882050, 181882298
];


var obj = {
	'play' : false,
	'track_count' : 0,
	'track_id' : undefined
};

function set_track_count(type){
	switch(type){
		case 'next':
			if (track_list[obj.track_count+1] != undefined) {
				obj.track_count++;
			}else{
				obj.track_count = 0;
			}
			break;

		case 'before':
			if (track_list[obj.track_count-1] != undefined) {
				obj.track_count--;
			}else{
				obj.track_count = track_list.length-1;
			}
			break;
	}
}

var autostart = false;

window.onload = function(){
	play();
}

function play(){
	SC.stream('/tracks/'+track_list[obj.track_count]).then(function(player){
		scplayer = player;
		
		document.getElementById('player-button').onclick = function(){
			if (!obj.play) {
				_play();
			}else{
				_pause();
			}	
		}

		if (autostart) {
			autostart = false;
			_play();
		}


		function _play(){
			obj.play = true;
			set_track_id_color(track_list[obj.track_count]);

    		player.play();
    		document.getElementById('status').innerHTML = obj.track_count;
    		
    	}

    	function _pause(){
    		obj.play = false;
    		player.pause();
    		console.log(player);
    	}

    	player.on('play-start', function(){
			// $.getJSON('https://api.soundcloud.com/tracks/'+obj.track_id+'?client_id=N2eHz8D7GtXSl6fTtcGHdSJiS74xqOUI', function(e){
			// 	document.getElementById('total_time').innerHTML = timecode(e.duration);
			// })
		});


    	player.on('time', function(e){
			document.getElementById('time').innerHTML = timecode(e);
			// document.getElementById('seek').value = e;

		});

		player.on('buffering_start', function(){
			document.getElementById('loading').style.display = 'block';
		});

		player.on('buffering_end', function(){
			document.getElementById('loading').style.display = 'none';
			document.getElementById('total_time').innerHTML = timecode(this.getDuration());
			// document.getElementById('seek').max = this.getDuration();
		});

		player.on('play-resume', function(){
			
		});
		

		player.on('finish', function(){
			player.kill();
			while(true){
				if (scplayer.isDead()) {
					alert('end');
					break;
				}	
			}
			set_track_count('next');
			autostart = true;
			play();
		});

		// document.getElementById('seek').onchange = function(){
		// 	player.seek(this.value);
		// 	// alert(this.value);
		// }

		document.getElementById('next').onclick = function(){
			player.kill();
			while(true){
				if (player.isDead()) break;
			}
			obj.play = false;
			autostart = true;
			set_track_count('next');
			play();
		}

		document.getElementById('before').onclick = function(){
			player.kill();
			obj.play = false;
			autostart = true;
			set_track_count('before');
			play();
		}
    })
}

var timecode = function(ms) {
var hms = function(ms) {
      return {
        h: Math.floor(ms/(60*60*1000)),
        m: Math.floor((ms/60000) % 60),
        s: Math.floor((ms/1000) % 60)
      };
    }(ms),
    tc = []; // Timecode array to be joined with '.'
	if (hms.h > 0) {
	  tc.push(hms.h);
	}

	tc.push((hms.m < 10 && hms.h > 0 ? "0" + hms.m : hms.m));
	tc.push((hms.s < 10  ? "0" + hms.s : hms.s));

	return tc.join(':');
};

function select_track_id(type){
	var this_track_num = track_list.indexOf(obj.track_id);
	if (type == 'next') {
		if (this_track_num >= track_list.length-1) {
			return track_list[0];
		}else{
			return track_list[this_track_num+1];
		}
	}else if(type == 'before'){
		if (this_track_num == -1) {
			return track_list[0];
		}else{
			if (this_track_num == 0) {
				return track_list[track_list.length-1];
			}else{
				return track_list[this_track_num-1];
			}	
		}
	}
}

function set_track_id_color(track_id){
	var list = document.getElementsByClassName('track-view-list');
	for (var i = 0; i <= list.length-1; i++) {
		document.getElementById(list[i].id).style.color = 'black';
	}
	document.getElementById(track_id).style.color = 'red';
}

(function () {
	var list = '';
	for (var i = 0; i <= track_list.length-1; i++) {
		list += '<div class="track-view-list" id="'+track_list[i]+'">'+track_list[i]+'</div>';
	}
	document.getElementById('list-view').innerHTML=list;
})()


function notifyMe() {
  // Let's check if the browser supports notifications
  if (!("Notification" in window)) {
    alert("This browser does not support desktop notification");
  }

  // Let's check whether notification permissions have already been granted
  else if (Notification.permission === "granted") {
    // If it's okay let's create a notification
    var notification = new Notification("Hi there!");
  }

  // Otherwise, we need to ask the user for permission
  else if (Notification.permission !== 'denied') {
    Notification.requestPermission(function (permission) {
      // If the user accepts, let's create a notification
      if (permission === "granted") {
        var notification = new Notification("Hi there!");
      }
    });
  }

  // At last, if the user has denied notifications, and you 
  // want to be respectful there is no need to bother them any more.
}
</script>
</body>
</html>

templates/sc.html
<!DOCTYPE html>
<html>
<head>
<script src="https://connect.soundcloud.com/sdk/sdk-3.3.0.js"></script>
</head>
<body>
<script>
SC.initialize({
	client_id: '7c76b10fd87a3f9cf91d51b9f8cf069c',
	redirect_uri: 'https://auth.dopehotz.com/callback/',
});

// initiate auth popup
SC.connect().then(function() {
	return SC.get('/me');
}).then(function(me) {
	alert('Hello, ' + me.username);
});

</script>
</body>
</html>

templates/test.html
<!DOCTYPE html>
<html>
<head>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/auth.css' %}">
	<title></title>
</head>
<body>
	<div class="test_lee"></div>
</body>
</html>